const schemaStatements = [
  `PRAGMA foreign_keys = ON;`,
  `CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK(role IN ('admin','operator','user')),
    status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','inactive','suspended')),
    account_type TEXT NOT NULL DEFAULT 'free' CHECK(account_type IN ('free','subscription')),
    current_credit INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS oauth_accounts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    provider TEXT NOT NULL CHECK(provider IN ('google')),
    provider_user_id TEXT NOT NULL,
    email TEXT NOT NULL,
    profile_json TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE(provider, provider_user_id)
  );`,
  `CREATE TABLE IF NOT EXISTS ai_providers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    driver TEXT NOT NULL,
    base_url TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','inactive')),
    description TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS provider_models (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    provider_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    model_code TEXT NOT NULL,
    is_default INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','inactive')),
    metadata_json TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(provider_id) REFERENCES ai_providers(id) ON DELETE CASCADE,
    UNIQUE(provider_id, model_code)
  );`,
  `CREATE TABLE IF NOT EXISTS system_api_keys (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    provider_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    encrypted_key TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','inactive')),
    usage_count INTEGER NOT NULL DEFAULT 0,
    last_used_at TEXT,
    error_count INTEGER NOT NULL DEFAULT 0,
    last_error_at TEXT,
    cooldown_until TEXT,
    is_rate_limited INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(provider_id) REFERENCES ai_providers(id) ON DELETE CASCADE
  );`,
  `CREATE TABLE IF NOT EXISTS subscription_packages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    package_type TEXT NOT NULL CHECK(package_type IN ('credit','duration','byok')),
    price_amount REAL NOT NULL DEFAULT 0,
    currency TEXT NOT NULL DEFAULT 'IDR',
    credit_amount INTEGER NOT NULL DEFAULT 0,
    duration_days INTEGER NOT NULL DEFAULT 0,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','inactive')),
    metadata_json TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS user_subscriptions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    package_id INTEGER NOT NULL,
    package_type TEXT NOT NULL CHECK(package_type IN ('credit','duration','byok')),
    status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','expired','cancelled','completed')),
    started_at TEXT NOT NULL,
    expires_at TEXT,
    credit_granted INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(package_id) REFERENCES subscription_packages(id) ON DELETE CASCADE
  );`,
  `CREATE TABLE IF NOT EXISTS user_byok_keys (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    provider_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    encrypted_key TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','inactive')),
    last_used_at TEXT,
    error_count INTEGER NOT NULL DEFAULT 0,
    last_error_at TEXT,
    cooldown_until TEXT,
    is_rate_limited INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(provider_id) REFERENCES ai_providers(id) ON DELETE CASCADE
  );`,
  `CREATE TABLE IF NOT EXISTS payment_methods (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    code TEXT NOT NULL UNIQUE,
    type TEXT NOT NULL,
    account_name TEXT,
    account_number TEXT,
    instructions TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','inactive')),
    metadata_json TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS orders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_number TEXT NOT NULL UNIQUE,
    user_id INTEGER NOT NULL,
    package_id INTEGER NOT NULL,
    payment_method_id INTEGER,
    package_name TEXT NOT NULL,
    package_type TEXT NOT NULL CHECK(package_type IN ('credit','duration','byok')),
    price_amount REAL NOT NULL,
    currency TEXT NOT NULL DEFAULT 'IDR',
    status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected','expired')),
    notes TEXT,
    rejection_reason TEXT,
    approved_by INTEGER,
    approved_at TEXT,
    expires_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(package_id) REFERENCES subscription_packages(id) ON DELETE RESTRICT,
    FOREIGN KEY(payment_method_id) REFERENCES payment_methods(id) ON DELETE SET NULL,
    FOREIGN KEY(approved_by) REFERENCES users(id) ON DELETE SET NULL
  );`,
  `CREATE TABLE IF NOT EXISTS order_payment_proofs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id INTEGER NOT NULL,
    file_path TEXT,
    original_name TEXT,
    mime_type TEXT,
    notes TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE
  );`,
  `CREATE TABLE IF NOT EXISTS metadata_generations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    provider_id INTEGER NOT NULL,
    provider_model_id INTEGER,
    key_source TEXT NOT NULL CHECK(key_source IN ('system','byok')),
    input_filename TEXT,
    mime_type TEXT,
    credit_used INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL CHECK(status IN ('success','failed')),
    request_payload TEXT,
    response_payload TEXT,
    error_message TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(provider_id) REFERENCES ai_providers(id) ON DELETE RESTRICT,
    FOREIGN KEY(provider_model_id) REFERENCES provider_models(id) ON DELETE SET NULL
  );`,
  `CREATE TABLE IF NOT EXISTS audit_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    actor_user_id INTEGER,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT,
    payload_json TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL
  );`,
  `CREATE TABLE IF NOT EXISTS app_settings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    group_key TEXT NOT NULL,
    setting_key TEXT NOT NULL UNIQUE,
    value_type TEXT NOT NULL CHECK(value_type IN ('string','number','boolean','json','secret')),
    value_text TEXT,
    default_value_text TEXT,
    is_public INTEGER NOT NULL DEFAULT 0,
    is_editable INTEGER NOT NULL DEFAULT 1,
    description TEXT,
    validation_rules TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS app_settings_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    setting_id INTEGER NOT NULL,
    old_value_text TEXT,
    new_value_text TEXT,
    changed_by INTEGER,
    created_at TEXT NOT NULL,
    FOREIGN KEY(setting_id) REFERENCES app_settings(id) ON DELETE CASCADE,
    FOREIGN KEY(changed_by) REFERENCES users(id) ON DELETE SET NULL
  );`,
  `CREATE TABLE IF NOT EXISTS coupons (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    discount_type TEXT NOT NULL CHECK(discount_type IN ('percentage','fixed')),
    discount_value REAL NOT NULL,
    min_purchase_amount REAL NOT NULL DEFAULT 0,
    max_discount_amount REAL,
    usage_limit INTEGER,
    usage_count INTEGER NOT NULL DEFAULT 0,
    usage_limit_per_user INTEGER NOT NULL DEFAULT 1,
    valid_from TEXT,
    valid_until TEXT,
    applicable_package_types TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','inactive','expired')),
    description TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS coupon_usages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    coupon_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    order_id INTEGER NOT NULL,
    discount_amount REAL NOT NULL,
    created_at TEXT NOT NULL,
    FOREIGN KEY(coupon_id) REFERENCES coupons(id) ON DELETE CASCADE,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,
    UNIQUE(coupon_id, order_id)
  );`,
];

module.exports = schemaStatements;